package za.ac.uct.primaryAlcohol;

import java.io.*;
import java.util.ArrayList;

/**
 * Bins all primary alcohol omega dihedhral angles in 1° intervals
 * @author marc
 *
 */
public class PrimAlcConfRatio {
	String filepath;
	
	
	public PrimAlcConfRatio(String filepath) {
		super();
		this.filepath = filepath;
	}
	
	public PrimAlcConfRatio() {
		super();
	}
	
	
	/**
	 * Method called to kick off the bin frequency calculation.<br />
	 * Calls other methods to manage entire process.
	 * @param infile list of frames and corresponding angles as generated by VMD (tab value separators replaced with space value separators)
	 * @throws Exception
	 */
	public void calcConfFrequencies(String infile) throws Exception {
		String line;
		String outfile = infile+"_primAlcFreq.dat";
		ArrayList<PrimAlcBin> aList = new ArrayList<PrimAlcBin>();
		initArrayList(aList);
		
		BufferedWriter bw = new BufferedWriter(new FileWriter(outfile));
		BufferedReader br = new BufferedReader(new FileReader(infile));
		
		while((line=br.readLine()) != null) {
			// ignore comment lines starting with hash
			if (line.startsWith("#"))
				continue;
			
			// ignore blank lines
			if (line.trim().length() == 0)
				continue;
			
			String[] tokens = line.split(" ");
			
			int roundAngle = Math.round(Float.parseFloat(tokens[1]));
			
			// if the rounded angle matches angles for any of the bins then increment the bin's frequency by 1
			for(int i=0; i<aList.size(); i++) {
				if(roundAngle==aList.get(i).getAngle())
					aList.get(i).incFreq();
			}
		}
		saveFrequencies(bw, aList);
	}
	
	/**
	 * Writes the bin frequencies to a file
	 * @param bw
	 * @param aList
	 * @throws Exception
	 */
	private void saveFrequencies(BufferedWriter bw, ArrayList<PrimAlcBin> aList) throws Exception {
		for(int i=0; i<aList.size(); i++) {
			bw.write(aList.get(i).getAngle()+" "+aList.get(i).getFrequency());
			bw.newLine();
		}
		bw.flush();
		bw.close();
	}
	
	/**
	 * Create the initial arrayList
	 * @param aList
	 * @return
	 */
	private ArrayList<PrimAlcBin> initArrayList(ArrayList<PrimAlcBin> aList) {
		for(int i=-180; i<=180; i++) {
			aList.add(new PrimAlcBin(i));
		}
		return aList;
	}
	

}
