package za.ac.uct.util;

import java.io.*;

/**
 * Grabs .dat file generated by xmgrace containing separate sets of coordinates
 * (1 for phi and 1 for psi) and merges them into one single dataset for scatter plot generation
 * @author marc
 *
 */
public class ScatterDataGenerator {
	
	private String grace;
	private String[][] array;
	
	public void run(String grace) {
		this.grace = grace;
		try {
			mergeGraceData();
			writeMergedGraceData(true);
			writeMergedGraceData(false);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * reads file, stores each line in String[][]
	 * when it gets to 2nd dataset (marked by blank line)
	 * it starts comparing and merging
	 * @throws Exception
	 */
	private void mergeGraceData() throws Exception {
		BufferedReader br = new BufferedReader(new FileReader(grace));
		String line = "";
		int i =0;
		
		// count number of lines in file
		while((line = br.readLine()).trim().length() != 0) {
			i++;
		}
		
		// reset for next read through
		br = new BufferedReader(new FileReader(grace));
		
		array = new String[i][3];
		
		// read in initial set of torsional angle values
		i = 0;
		while((line = br.readLine()).length() != 0) {
			String[] tmp = line.split(" ");
			// set frame number to 0 column
			//array[i][0] = tmp[0];
			// used for glycam runs to remove pdb record (not part of trajectory so can't include)
			array[i][0] = Integer.toString(i);
			// set first angle to 1 column (will be phi)
			array[i][1] = tmp[1];
			i++;
		}
		
		
		// continue on with reading second set of values
		i = 0;
		while((line = br.readLine()) != null) {
			// ignore blank lines
			if (line.trim().length() == 0)
				continue;
			//System.out.println(line);
			
			String[] tmp = line.split(" ");
			// set angle to 2 column (will be psi)
			array[i][2] = tmp[1];
			//System.out.println("DEBUG -- "+i+" "+array[i][2]);
			i++;
		}
		br.close();
	}
	
	
	/**
	 * Writes the array to a file so that it can be displayed using gnuplot
	 * (original input file name with "Merged.dat" appended).
	 * If frames==false then frame numbers are not included in the file.
	 * Otherwise frame numbers are included.
	 * @throws Exception
	 */
	private void writeMergedGraceData(boolean frames) throws Exception {
		String tmp = "";
		BufferedWriter bw;
		
		
		if(frames==false) {
			tmp =  grace.substring(0, grace.length()-4) + "Merged.dat";
			bw = new BufferedWriter(new FileWriter(tmp));
			for(int i=0; i<array.length; i++) {
				bw.write(array[i][1]+" "+array[i][2]);
				bw.newLine();
				bw.flush();
			}
		} else {
			tmp =  grace.substring(0, grace.length()-4) + "MergedWithFrames.dat";
			bw = new BufferedWriter(new FileWriter(tmp));
			for(int i=0; i<array.length; i++) {
				bw.write(array[i][0]+" "+array[i][1]+" "+array[i][2]);
				bw.newLine();
				bw.flush();
			}
		}
		
		bw.close();
	}
	
}
